title = "Porfa XYZ"
baseURL = "https://www.porfa.xyz"
theme = "minimo"
defaultContentLanguage = "pt-br"
#disqusShortname = "www-porfa-xyz"
Paginate = 5
preserveTaxonomyNames = true
enableRobotsTXT = true 
pygmentsCodefences = true
enableEmoji = true

[params.info]
description = "404, Bio not found"
title404 = "Nothing's here!"

[params.copyright]
holder = "Porfa -"
startYear = "2022"
suffix = "Powered by Github Pages, Hugo and Minimo."

[params.social]
email = "porfaxyz@gmail.com"
github = "porfaxyz"
#gitlab = "porfaxyz"
#instagram = "porfaxyz"
#twitter = "porfaxyz"
#youtube = "UCBrKT_aELMXWbWfUcgw63dg"

[params.comments]
enable = true

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"] # used in 404 template ( Generator: https://gopherize.me )

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#34D399"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","taxonomy_cloud","sidebar_menu"]
footer = ["social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.search]
client = "fuse" # algolia / fuse / lunr

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.pt-br]
lang = "pt-BR"
languageName = "Portuguese Brazilian"
weight = 1
